apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-fss-pvc
  namespace: jenkins-test
spec:
  storageClassName: jenkins-fss
  accessModes:
    - ReadWriteMany
  resources:
    requests:
    # Although storage is provided here it is not used for FSS file systems
      storage: 50Gi
  volumeName: jenkins-fss-pv 