apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-fss-pv
spec:
  storageClassName: jenkins-fss
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany 
  mountOptions:
    - nosuid  
  nfs:
# Replace this with the IP of your FSS file system in OCI  
    server: 10.253.162.103
# Replace this with the Path of your FSS file system in OCI    
    path: "/jenkins-nfs-new"
    readOnly: false 