kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
    name: examplename-pvc-nfs-static 
spec:
    accessModes: 
        - ReadWriteMany 
    resources: 
        requests: 
            storage: 10Gi
    volumeName: pv-nfs-examplename # make sure specfied volumeName matches the name of the PersistentVolume you created
    storageClassName: ""