apiVersion: storage.k8s.io/v1 
kind: StorageClass 
metadata:
    name: example-nfs-classname 
    namespace: example-namespace 
provisioner: nfs.csi.k8s.io 
parameters: 
    server: gateway-dns-name-or-ip-address 
    share: /example-share-name 
reclaimPolicy: Retain 
volumeBindingMode: Immediate
mountOptions: 
    - hard 
    - nfsvers=4.1